In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('../../data/raw/NSE.csv')
df = df[df['instrument_type'] == 'EQUITY']
df.head()

,instrument_key,exchange_token,tradingsymbol,name,last_price,expiry,strike,tick_size,lot_size,instrument_type,option_type,exchange
2,NSE_EQ|INE869I01013,21195,GTPL,GTPL HATHWAY LIMITED,119.06,NaN,NaN,0.01,1.0,EQUITY,NaN,NSE_EQ
7,NSE_EQ|INE399C01030,11689,SUPRAJIT,SUPRAJIT ENGINEERING LTD,462.15,NaN,NaN,0.05,1.0,EQUITY,NaN,NSE_EQ
8,NSE_EQ|INE0MJQ01020,12986,PRITIKA,PRITIKA ENG COMPO LTD,76.80,NaN,NaN,0.05,2000.0,EQUITY,NaN,NSE_EQ
9,NSE_EQ|INE0LLY01014,27213,EIEL,ENVIRO INFRA ENGINEERS L,235.40,NaN,NaN,0.01,1.0,EQUITY,NaN,NSE_EQ
10,NSE_EQ|INE0J1E01027,10293,KCK,KCK INDUSTRIES LTD,44.35,NaN,NaN,0.05,2500.0,EQUITY,NaN,NSE_EQ